apiVersion: "v1"
kind: Pod
metadata:
  name: pv-extract
spec:
  containers:
    - name: pv-extract-pod
      image: <registry-fqdn:port>/ubi8/ubi
      command: ["sleep", "3000"]
      volumeMounts:
        - mountPath: "/master-scan-results"
          name: master-scan-vol
  volumes:
    - name: master-scan-vol
      persistentVolumeClaim:
        claimName: rhcos4-e8-master
