apiVersion: compliance.openshift.io/v1alpha1
kind: ScanSettingBinding
metadata:
  name: moderate-compliance-requirements
profiles:
  - apiGroup: compliance.openshift.io/v1alpha1
    kind: Profile
    name: rhcos4-stig-v2r1
  - apiGroup: compliance.openshift.io/v1alpha1
    kind: Profile
    name: ocp4-stig-v2r1
settingsRef:
  apiGroup: compliance.openshift.io/v1alpha1
  kind: ScanSetting
  name: stig
