# AWS EFS PersistentVolume, PersistentVolumeClaim, and Pod Deployment
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-pvc
  namespace: testproject
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efsv2-csi-aws-com
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-pvc-v2
  namespace: testproject
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efsv2-csi-aws-com
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Pod
metadata:
  name:  test-pod-new
  namespace: testproject
spec:
  containers:
    - name: my-test-container
      image: registry.redhat.io/ubi8/ubi-minimal:latest
      command: ["/bin/sh", "-c", "sleep 3600"]
      volumeMounts:
        - name: efs-storage
          mountPath: /mnt/testmount
        - name: efs-storage2
          mountPath: /mnt/testmount2
  volumes:
    - name: efs-storage
      persistentVolumeClaim:
        claimName: efs-pvc
    - name: efs-storage2
      persistentVolumeClaim:
        claimName: efs-pvc-v2

---
apiVersion: v1
kind: Pod
metadata:
  name:  test-pod-new2
  namespace: testproject
spec:
  containers:
    - name: my-test-container
      image: registry.redhat.io/ubi8/ubi-minimal:latest
      command: ["/bin/sh", "-c", "sleep 3600"]
      volumeMounts:
        - name: efs-storage
          mountPath: /mnt/testmount
        - name: efs-storage2
          mountPath: /mnt/testmount2
  volumes:
    - name: efs-storage
      persistentVolumeClaim:
        claimName: efs-pvc
    - name: efs-storage2
      persistentVolumeClaim:
        claimName: efs-pvc-v2

