apiVersion: v1alpha1
kind: AgentConfig
metadata:
  name: agent-config 
additionalNTPSources:
  - 0.north-america.pool.ntp.org
  - 1.north-america.pool.ntp.org
rendezvousIP: 192.168.1.80  # Pick an IP of one of the control plane servers
hosts:
  - hostname: master-0
    role: master
    interfaces:
      - name: eno1  # This doesn't need to be the actual interface name, it has to match the names below
        macAddress: 00:ef:44:21:e6:a6
    rootDeviceHints:
      deviceName: /dev/sda # Change this to the drive that OCP should install the OS on
    networkConfig:
      interfaces:
        - name: eno1.300  # Name of interface, recommend naming same as vlan
          type: vlan
          state: up
          vlan:
            base-iface: eno1
            id: 300
          ipv4:
            enabled: true
            address:
              - ip: 10.10.10.14
                prefix-length: 24
            dhcp: false
        - name: eno1
          type: ethernet
          state: up
          mac-address: 00:ef:44:21:e6:a6  # This should be one of the mac addresses from above
          mtu: 9000     # Needed only if Jumbo frames are configured
          ipv4:
            enabled: false
          ipv6:
            enabled: false
      dns-resolver:
        config:
          server:
            - 192.168.1.1
      routes:
        config:
          - destination: 0.0.0.0/0
            next-hop-address: 192.168.1.1
            next-hop-interface: bond0 # Match the name of the bond vlan interface
            table-id: 254
#####
  - hostname: worker-0
    role: worker
    interfaces:
      - name: eno1  # This doesn't need to be the actual interface name, it has to match the names below
        macAddress: 00:ef:44:21:e6:a6
    rootDeviceHints:
      deviceName: /dev/sda # Change this to the drive that OCP should install the OS on
    networkConfig:
      interfaces:
        - name: eno1.300  # Name of interface, recommend naming same as vlan
          type: vlan
          state: up
          vlan:
            base-iface: eno1
            id: 300
          ipv4:
            enabled: true
            address:
              - ip: 10.10.10.15
                prefix-length: 24
            dhcp: false
        - name: eno1
          type: ethernet
          state: up
          mac-address: 00:ef:44:21:e6:a6  # This should be one of the mac addresses from above
          mtu: 9000
          ipv4:
            enabled: false
          ipv6:
            enabled: false
      dns-resolver:
        config:
          server:
            - 192.168.1.1
      routes: 
        config:
          - destination: 0.0.0.0/0
            next-hop-address: 192.168.1.1
            next-hop-interface: bond0 # Match the name of the bond vlan interface
            table-id: 254
