---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: project-pvc
spec:
  storageClassName: gp2-csi
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Pod
metadata:
  name:  test-pod
spec:
  containers:
    - name: my-test-container
      image: registry.redhat.io/ubi8/ubi-minimal:latest
      command: ["/bin/sh", "-c", "sleep 3600"]
      volumeMounts:
        - name: test-storage
          mountPath: /mnt/testmount
  volumes:
    - name: test-storage
      persistentVolumeClaim:
        claimName: project-pvc
