apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: defualt
  name: datavolume-cloner
subjects:
- kind: ServiceAccount
  name: default 
roleRef:
  kind: ClusterRole
  name: datavolume-cloner 
  apiGroup: rbac.authorization.k8s.io
