apiVersion: metallb.io/v1beta1
kind: MetalLB
metadata:
  name: metallb
  namespace: metallb-system
spec:
  nodeSelector:  
    node-role.kubernetes.io/master: ""
  speakerTolerations:   
  - key: "Example"
    operator: "Exists"
    effect: "NoExecute"
