apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ontap-nfs-gold
provisioner: csi.trident.netapp.io
allowVolumeExpansion: true
parameters:
  backendType: "ontap-nas"   # This should be a storage type in NetApp like, ontap-nas, o
  media: "ssd"               # This should match the drive types in the NetApp storage array, typically ssd or nvme
  provisioningType: "thin"   # Some backends support only thin, only thick, or both
  snapshots: "true"          # Most backends support snapshots.
