apiVersion: v1
kind: Namespace
metadata:
  name: rhokp
---
apiVersion: v1
kind: Service
metadata:
  name: rhokp
  namespace: rhokp
  labels:
    app: rhokp-app
spec:
  ports:
    - name: https
      port: 8443
      targetPort: 8443
  selector:
    app: rhokp-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rhokp-server
  namespace: rhokp
  labels:
    app: rhokp-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rhokp-app
  template:
    metadata:
      labels:
        app: rhokp-app
    spec:
      containers:
      - name: rhokp
        image: registry.redhat.io/offline-knowledge-portal/rhokp-rhel9:latest  # set image to the disconnected registry image
        env:
        - name: ACCESS_KEY
          value: "Change Me" # Replace this!
        ports:
        - name: https
          containerPort: 8443
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: rhokp
  namespace: rhokp
  labels:
    app: rhokp-app
spec:
  to:
    kind: Service
    name: rhokp
  port:
    targetPort: https
  tls:
    termination: passthrough
